### PR TITLE
Upgrade dependencies and build

### PR DESCRIPTION
**Pull request by dennisreimann**
Maintenance and testing the new Netflify deploy preview :)

### CODE REVIEW

**Comment by Zaxounette** [comment]
I was gonna ask if you changed the tests ! 

Nice ! 
Worked perfectly for #209 !

**Comment by Zaxounette** [comment]
Also, is this a test environment that could be added to the doc repo ? Or is it something totally unrelated ?

**Comment by dennisreimann** [comment]
@Zaxounette Yes, @pavlenex brought it up yesterday and I added it here because I encountered trouble setting it up for the docs. Now that I know it works here and the config should be ok like this, I'll tinker some more in the docs repo.

Would also be good to add the preview feature for the website and foundation site too.

**Comment by Zaxounette** [comment]
> @pavlenex brought it up yesterday 

Ah I expected as much ! 
I remember seing these tests in the bitcoin_design repos.

**Pull request merged**
