### PR TITLE
Update List.js

### LINKED ISSUE #292: New entry submission - Chroma
New submission:

Name: Chroma
Url: https://getchroma.co
Type: merchants - health-household
Description: Chroma manufactures and sells the most advanced UV, Near Infrared, and Red Light Therapy products in the world, in addition to best in class blue light blockers. BTC/LN payments receive a 12.9% discount on all items.

### LINKED ISSUE #294: New entry submission - Bitgild
New submission:

Name: Bitgild
Url: https://www.bitgild.com
Type: merchants - jewelry
Description: Buy physical gold and silver with bitcoin

### LINKED ISSUE #295: New entry submission - Koined Store
New submission:

Name: Koined Store
Url: https://koined.store
Type: merchants - cryptocurrency-paraphernalia
Description: Merch store accepting payments through our own BTCPayServer - No third party.

### LINKED ISSUE #296: New entry submission - Chef Marvin Gauci
New submission:

Name: Chef Marvin Gauci
Url: https://marvingauci.com
Type: apps
Description: Malta’s gastronomic icon Chef Marvin Gauci, accepts bitcoin payments through BTCPay in all his restaurants.

### LINKED ISSUE #297: Update url - bitpaint
I just updated the domain name to https://btcpay.bitpaint.club/ , can you update it, too?
https://github.com/btcpayserver/directory.btcpayserver.org/issues/180#issuecomment-1061936798

### LINKED ISSUE #298: New entry submission - BTCPay Bulgaria
New submission:

Name: BTCPay Bulgaria
Url: https://btcpay.bg
Type: hosts
Description: Helping local businesses in accepting BTC payments for their products and services via BTCPayServer.

Integration and shared BTCPay hosting is payable via BTCPayServer only.

### LINKED ISSUE #301: New entry submission - Code Engine
New submission:

Name: Code Engine
Url: https://codeengine.com.au
Type: merchants - services
Description: Custom Software Solutions

### LINKED ISSUE #302: New entry submission - Bitcoin Bloem
New submission:

Name: Bitcoin Bloem
Url: https://www.bitcoinbloem.com/
Type: merchants - health-household
Description: Flowers are beautiful and make people happy. It shows appreciation for one another. Flowers are a waste of energy to grow, so it should be forbidden. We offer you flowers for your bitcoin. Try it, take care of the people close to you. Give flowers.

### LINKED ISSUE #303: New entry submission - Bitcoin Brabant
New submission:

Name: Bitcoin Brabant
Url: https://bitcoinbrabant.com/
Type: merchants - electronics
Description: Mining stuff, official reseller of foundation passport and cryptotag.

### LINKED ISSUE #306: New entry submission - Biker for Kids e.V.
New submission:

Name: Biker for Kids e.V.
Url: https://www.km-projektplan.de/biker-for-kids-cologne-e-v/
Type: non-profits
Description: Biker For Kids Cologne e.V. freut sich über Ihre Spende per Bitcoin oder Lightning.
Herzlich willkommen bei den Biker-Weihnachtsmännern. Jedes Jahr in der Vorweihnachtszeit und zu besonderen Anlässen, sind die Weihnachtsmänner unterwegs, um Spenden

### LINKED ISSUE #307: New entry submission - FULMO
New submission:

Name: FULMO
Url: https://shop.fulmo.org
Type: merchants - electronics
Description: Buy Bitcoin Lightning Nodes, Lightning ATMs and other hardware related to the Bitcoin Lightning network.

### PR DESCRIPTION
**Pull request by pavlenex**
Close #292
Close #294
Close #295
Close #296
Close #297
Close #298
Close #301
Close #302
Close #303
Close #306
Close #307

Please squash before merging. Build is failing, I do not know why.

### CODE REVIEW

**Comment by pavlenex** [comment]
@dennisreimann dammit I cannot figure out what I did wrong here and why the deploy is failing. Can you halp?

**Comment by pavlenex** [comment]
@dennisreimann No idea what I'm doing wrong and why the build is failing, if you can halp on this one would appreciate it.

**Comment by pavlenex** [comment]
omg thanks @dennisreimann I thought it was me being dumb and making a syntax error. Is the token similar problem we're facing with calendar in oragnization repo?

Thanks!

**Comment by dennisreimann** [comment]
Nope, that wasn't related to the token, but to a dependency being outdated and crashing the Netlify build. While I was at it, I also updated the build for this repo.

**Pull request merged**
