### PR TITLE
Capitalize, sort by name

### PR DESCRIPTION
**Pull request by nosovk**

### CODE REVIEW

**Comment by Zaxounette** [comment]
This is of no effect, what appears in the front-end is randomized so to not give importance to any entries, since we don't "vet" them.

**Comment by Zaxounette** [comment]
Also, you have 200 lines missing in the list.js file compared to master.

**Comment by nosovk** [comment]
yep, something missing, will redo later today.
There are also tabs\spaces and other styling issues.

**Comment by Zaxounette** [comment]
In all honesty, don't bother.
The entries have been added primarily at the end of the file, one beneath the other, without any consideration for alphabetical order, since we provide a randomized view on the front-end each time you refresh or scroll down.

**Comment by nosovk** [comment]
then won't do :)

**Pull request closed without merging**
